In [ ]:
# Importing Libraries

import pandas as pd
import numpy as np

### Read the file

In [ ]:
data=pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas (2).csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Display the first five rows of the data

data.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
# Using conditional statements split the column location to location and symbol

data['Location'] = data['Location'].str.strip()  # Remove leading and trailing spaces

def splitting(val):
  if ',' in val and ' ' in val:
    return val.split(',')
  elif ' ' in val and ',' not in val:
    return val.split(' ')
  elif ',' in val and ' ' not in val:
    return val.split(',')
data[['Location','Symbol']]=[splitting(x) for x in data['Location']]

In [ ]:
# Avoiding inconsistencies in the column names

data.columns=data.columns.str.replace(" ","_")

##Let us check NULL values

In [ ]:
data.isnull().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy_Apply     0
Symbol         0
dtype: int64

In [ ]:
data.Age.fillna(data.Age.mean(),inplace=True)

In [ ]:
data.Rating.fillna(data.Rating.mean(),inplace=True)

In [ ]:
data.isnull().sum()

Index          0
Age            0
Salary         0
Rating         0
Location       0
Established    0
Easy_Apply     0
Symbol         0
dtype: int64

In [ ]:
# Replacing '-1' with 'False' and converting the column ini=to 'Boolean'

data.columns
data['Easy_Apply']=data['Easy_Apply'].replace("-1","False")
data['Easy_Apply']=data['Easy_Apply'].replace("TRUE","True")
def true_false(val):
  if val.lower()=='false':
    return False
  else:
    return True
data['Easy_Apply']=[true_false(x) for x in data['Easy_Apply']]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          29 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       29 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy_Apply   29 non-null     bool
 7   Symbol       29 non-null     object
dtypes: bool(1), float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [ ]:
# rounding the age column into one decimal for consistency

data.Age=data.Age.round(decimals=1)

In [ ]:
# Finding outliers for the data considering Age, Rating and Salary

q1=data[['Age','Salary','Rating']].quantile(0.25)
q3=data[['Age','Salary','Rating']].quantile(0.75)
IQR=q3-q1
outliers=((data[['Age','Salary','Rating']]<(q1-1.5*IQR)) | (data[['Age','Salary','Rating']]>(q3+1.5*IQR)))
print(data[outliers.any(axis=1)])

    Index   Age     Salary  Rating   Location  Established  Easy_Apply Symbol
1       1  66.0  $55k-$66k     3.5   New York         2002        True     Ny
3       3  64.0  $44k-$99k     4.4      India         1988       False     In
14     14  66.0  $44k-$99k     4.0  Australia         2020        True    Aus
24     24  13.0  $44k-$99k    -1.0   New York         1987       False     Ny

<ipython-input-14-cab6f20ad186>:3: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  q1=data[['Age','Salary','Rating']].quantile(0.25)
<ipython-input-14-cab6f20ad186>:4: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  q3=data[['Age','Salary','Rating']].quantile(0.75)
<ipython-input-14-cab6f20ad186>:6: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  outliers=((data[['Age','Salary','Rating']]<(q1-1.5*IQR)) | (data[['Age','Salary','Rating']]>(q3+1.5*IQR)))
<ipython-input-14-cab6f20ad186>:6: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  outliers=((data[['Age','Salary','Rating']]<(q1-1.5*IQR)) | (data[['Age','Salary','Rating']]>(q3+1.5*IQR)))

In [ ]:
# Replacing '$' with empty space and 'k' with '000' for consistency and understanding.

data["Salary"]=data["Salary"].str.replace("$","")
data["Salary"]=data["Salary"].str.replace("k","000")
data.head()

<ipython-input-15-7b681e0ad83d>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data["Salary"]=data["Salary"].str.replace("$","")

   Index   Age       Salary  Rating   Location  Established  Easy_Apply Symbol
0      0  44.0  44000-99000     5.4      India         1999        True     In
1      1  66.0  55000-66000     3.5   New York         2002        True     Ny
2      2  39.0  77000-89000    -1.0   New York           -1       False     Ny
3      3  64.0  44000-99000     4.4      India         1988       False     In
4      4  25.0  44000-99000     6.4  Australia         2002       False    Aus

In [ ]:
data['Established']=data['Established'].replace(-1,np.nan)

In [ ]:
# As we dont know the established year we cant replace that with a value using cenral tendencies so we will make that '-1' to unknown

data['Established']=data['Established'].replace(np.nan,"Unknown")

In [ ]:
#rounding the Rating column upto one decimal.

data.Rating=data.Rating.round(decimals=1)

In [ ]:
# Some people gave rating less than zero we will make hem zero by replacing '-1'

data['Rating']=data['Rating'].replace(-1.0,0.0)

In [ ]:
# Analyze the information of the data

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          29 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       29 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     object
 6   Easy_Apply   29 non-null     bool
 7   Symbol       29 non-null     object
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 1.7+ KB

In [ ]:
#Observe the analysis and statistics of the data

data.describe()

           Index        Age     Rating
count  29.000000  29.000000  29.000000
mean   14.000000  39.034483   3.665517
std     8.514693  13.973145   2.554586
min     0.000000  13.000000   0.000000
25%     7.000000  32.000000   1.400000
50%    14.000000  39.000000   4.000000
75%    21.000000  44.000000   5.400000
max    28.000000  66.000000   7.800000

In [ ]:
# SPlit the column Salary into two columns as 'salary_range_start' and 'salary_range_end'

data[["salary_range_start","salary_range_end"]]=data['Salary'].str.split('-',expand=True)

In [ ]:
# for consistency and integrity remove the column 'Salary'

del data['Salary']

In [ ]:
# To avoid confusion remove the column Index.

del data['Index']

In [ ]:
# Finally observe the data.

data.loc[:,['Age','Rating','Location','Symbol','salary_range_start','salary_range_end','Established','Easy_Apply']]

,Age,Rating,Location,Symbol,salary_range_start,salary_range_end,Established,Easy_Apply
0,44.0,5.4,India,In,44000,99000,1999.0,True
1,66.0,3.5,New York,Ny,55000,66000,2002.0,True
2,39.0,0.0,New York,Ny,77000,89000,Unknown,False
3,64.0,4.4,India,In,44000,99000,1988.0,False
4,25.0,6.4,Australia,Aus,44000,99000,2002.0,False
5,44.0,1.4,India,In,77000,89000,1999.0,True
6,21.0,0.0,New York,Ny,44000,99000,Unknown,False
7,44.0,0.0,Australia,Aus,44000,99000,Unknown,False
8,35.0,5.4,New York,Ny,44000,99000,Unknown,False
9,22.0,7.7,India,In,44000,99000,Unknown,True
10,55.0,5.4,India,In,10000,49000,2008.0,True
11,44.0,6.7,India,In,10000,49000,2009.0,False
12,39.0,0.0,India,In,44000,99000,1999.0,False
13,25.0,0.0,Australia,Aus,44000,99000,2019.0,True
14,66.0,4.0,Australia,Aus,44000,99000,2020.0,True
15,44.0,3.0,Australia,Aus,88000,101000,1999.0,False
16,19.0,4.5,India,In,19000,40000,1984.0,False
17,39.0,5.3,New York,Ny,44000,99000,1943.0,True
18,35.0,6.7,New York,Ny,44000,99000,1954.0,True
19,32.0,3.3,New York,Ny,44000,99000,1955.0,True
20,39.0,5.7,New York,Ny,44000,99000,1944.0,True
21,35.0,5.0,New York,Ny,44000,99000,1946.0,False
22,19.0,7.8,New York,Ny,55000,66000,1988.0,True
23,39.0,2.4,New York,Ny,44000,99000,1999.0,True
24,13.0,0.0,New York,Ny,44000,99000,1987.0,False
25,55.0,0.0,Australia,Aus,44000,99000,1980.0,True
26,39.0,3.5,India,In,55000,66000,1934.0,True
27,52.0,5.4,India,In,44000,99000,1935.0,False
28,39.0,3.4,Australia,Aus,39000,88000,1932.0,False

In [ ]:
data['salary_range_start'] = data['salary_range_start'].astype('int')
data['salary_range_end'] = data['salary_range_end'].astype('int')
data['Location'] = data['Location'].astype('string')
data['Established'] = data['Established'].astype('string')
data['Symbol'] = data['Symbol'].astype('string')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 29 non-null     float64
 1   Rating              29 non-null     float64
 2   Location            29 non-null     string
 3   Established         29 non-null     string
 4   Easy_Apply          29 non-null     bool
 5   Symbol              29 non-null     string
 6   salary_range_start  29 non-null     int64
 7   salary_range_end    29 non-null     int64
dtypes: bool(1), float64(2), int64(2), string(3)
memory usage: 1.7 KB

#NEW DATA----- chipotle dataset

In [ ]:
# Read the file

data1=pd.read_csv("/content/chipotle (1).tsv",sep='\t')

In [ ]:
# Display the fisrt 5 rows of the data

data1.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
# check for null values

data1.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
# Replace '$' symbol in 'item_price with '' and change the data type from string to 'boolean'

data1['item_price']=data1['item_price'].str.replace("$","")

<ipython-input-31-7e1ff8cc9a54>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data1['item_price']=data1['item_price'].str.replace("$","")

In [ ]:
data1['item_price']=data1['item_price'].astype(float)

In [ ]:
# Display the information of the table.

data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

In [ ]:
# check for duplicates in the data

data1.duplicated().any()

True

In [ ]:
# to know the rows and columns number before dropping duplicates.

data1.shape

(4622, 5)

In [ ]:
#Drop the duplicates from the data

data1=data1.drop_duplicates()

In [ ]:
#Reset the index of the data

data1=data1.reset_index(drop=True)

In [ ]:
# check the shape of the data

data1.shape

(4563, 5)

In [ ]:
# Observe the statistics of the data

data1.describe()

          order_id     quantity   item_price
count  4563.000000  4563.000000  4563.000000
mean    927.045803     1.076704     7.490083
std     528.936100     0.412739     4.244155
min       1.000000     1.000000     1.090000
25%     476.500000     1.000000     3.750000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [ ]:
# replace '[' and ']' with '' for the column 'choice_description'

data1['choice_description']=data1['choice_description'].str.replace('[',"")

<ipython-input-40-531543226d9e>:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data1['choice_description']=data1['choice_description'].str.replace('[',"")

In [ ]:
data1['choice_description']=data1['choice_description'].str.replace(']',"")
data1['choice_description']=data1['choice_description'].str.replace('-',"")

<ipython-input-41-d5c310f2826f>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data1['choice_description']=data1['choice_description'].str.replace(']',"")

In [ ]:
# enter different number of choices to convert the column of lists to rows of choices

data1[['1_choice','2_choice','3_choice','4_choice','5_choice','6_choice','7_choice','8_choice','9_choice','10_choice']]=data1['choice_description'].str.split(',',expand=True)

In [ ]:
# To maintain integrity delete the column 'choice_description'.

del data1['choice_description']

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4563 entries, 0 to 4562
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    4563 non-null   int64
 1   quantity    4563 non-null   int64
 2   item_name   4563 non-null   object
 3   item_price  4563 non-null   float64
 4   1_choice    3335 non-null   object
 5   2_choice    2804 non-null   object
 6   3_choice    2722 non-null   object
 7   4_choice    2522 non-null   object
 8   5_choice    2075 non-null   object
 9   6_choice    1321 non-null   object
 10  7_choice    605 non-null    object
 11  8_choice    179 non-null    object
 12  9_choice    49 non-null     object
 13  10_choice   4 non-null      object
dtypes: float64(1), int64(2), object(11)
memory usage: 499.2+ KB

In [ ]:
# fii the null values with 'None to avoid nan in the data

data1['1_choice']=data1['1_choice'].fillna("None")
data1['2_choice']=data1['2_choice'].fillna("None")
data1['3_choice']=data1['3_choice'].fillna("None")
data1['4_choice']=data1['4_choice'].fillna("None")
data1['5_choice']=data1['5_choice'].fillna("None")
data1['6_choice']=data1['6_choice'].fillna("None")
data1['7_choice']=data1['7_choice'].fillna("None")
data1['8_choice']=data1['8_choice'].fillna("None")
data1['9_choice']=data1['9_choice'].fillna("None")
data1['10_choice']=data1['10_choice'].fillna("None")

In [ ]:
data1['1_choice'] = data1['1_choice'].astype('string')
data1['2_choice'] = data1['2_choice'].astype('string')
data1['3_choice'] = data1['3_choice'].astype('string')
data1['4_choice'] = data1['4_choice'].astype('string')
data1['5_choice'] = data1['5_choice'].astype('string')
data1['6_choice'] = data1['6_choice'].astype('string')
data1['7_choice'] = data1['7_choice'].astype('string')
data1['8_choice'] = data1['8_choice'].astype('string')
data1['9_choice'] = data1['9_choice'].astype('string')
data1['10_choice'] = data1['10_choice'].astype('string')
data1['item_name'] = data1['item_name'].astype('string')

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4563 entries, 0 to 4562
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    4563 non-null   int64
 1   quantity    4563 non-null   int64
 2   item_name   4563 non-null   string
 3   item_price  4563 non-null   float64
 4   1_choice    4563 non-null   string
 5   2_choice    4563 non-null   string
 6   3_choice    4563 non-null   string
 7   4_choice    4563 non-null   string
 8   5_choice    4563 non-null   string
 9   6_choice    4563 non-null   string
 10  7_choice    4563 non-null   string
 11  8_choice    4563 non-null   string
 12  9_choice    4563 non-null   string
 13  10_choice   4563 non-null   string
dtypes: float64(1), int64(2), string(11)
memory usage: 499.2 KB

In [ ]:
df_1=(data1.query("quantity==1")
.groupby('item_name')['item_price'].mean())

In [ ]:
df_1.info()

<class 'pandas.core.series.Series'>
Index: 50 entries, 6 Pack Soft Drink to Veggie Soft Tacos
Series name: item_price
Non-Null Count  Dtype
--------------  -----
50 non-null     float64
dtypes: float64(1)
memory usage: 800.0 bytes

In [ ]:
# For Understanding place the item_price at the last

data1.loc[:,['order_id','quantity','item_name','1_choice','2_choice','3_choice','4_choice','5_choice','6_choice','7_choice','8_choice','9_choice','10_choice','item_price']]

,order_id,quantity,item_name,1_choice,2_choice,3_choice,4_choice,5_choice,6_choice,7_choice,8_choice,9_choice,10_choice,item_price
0,1,1,Chips and Fresh Tomato Salsa,None,None,None,None,None,None,None,None,None,None,2.39
1,1,1,Izze,Clementine,None,None,None,None,None,None,None,None,None,3.39
2,1,1,Nantucket Nectar,Apple,None,None,None,None,None,None,None,None,None,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,None,None,None,None,None,None,None,None,None,2.39
4,2,2,Chicken Bowl,TomatilloRed Chili Salsa (Hot),Black Beans,Rice,Cheese,Sour Cream,None,None,None,None,None,16.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4558,1833,1,Steak Burrito,Fresh Tomato Salsa,Rice,Black Beans,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,11.75
4559,1833,1,Steak Burrito,Fresh Tomato Salsa,Rice,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,None,11.75
4560,1834,1,Chicken Salad Bowl,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Guacamole,Lettuce,None,None,None,None,None,11.25
4561,1834,1,Chicken Salad Bowl,Fresh Tomato Salsa,Fajita Vegetables,Lettuce,None,None,None,None,None,None,None,8.75
4562,1834,1,Chicken Salad Bowl,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Lettuce,None,None,None,None,None,None,8.75

In [ ]:
merged_df = pd.merge(data1, df_1, how='left', on='item_name', suffixes=('', 'quantity'))

In [ ]:
merged_df

,order_id,quantity,item_name,item_price,1_choice,2_choice,3_choice,4_choice,5_choice,6_choice,7_choice,8_choice,9_choice,10_choice,item_pricequantity
0,1,1,Chips and Fresh Tomato Salsa,2.39,None,None,None,None,None,None,None,None,None,None,2.739143
1,1,1,Izze,3.39,Clementine,None,None,None,None,None,None,None,None,None,3.390000
2,1,1,Nantucket Nectar,3.39,Apple,None,None,None,None,None,None,None,None,None,3.390000
3,1,1,Chips and Tomatillo-Green Chili Salsa,2.39,None,None,None,None,None,None,None,None,None,None,2.390000
4,2,2,Chicken Bowl,16.98,TomatilloRed Chili Salsa (Hot),Black Beans,Rice,Cheese,Sour Cream,None,None,None,None,None,9.674035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4558,1833,1,Steak Burrito,11.75,Fresh Tomato Salsa,Rice,Black Beans,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,9.999255
4559,1833,1,Steak Burrito,11.75,Fresh Tomato Salsa,Rice,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,None,9.999255
4560,1834,1,Chicken Salad Bowl,11.25,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Guacamole,Lettuce,None,None,None,None,None,9.806701
4561,1834,1,Chicken Salad Bowl,8.75,Fresh Tomato Salsa,Fajita Vegetables,Lettuce,None,None,None,None,None,None,None,9.806701
4562,1834,1,Chicken Salad Bowl,8.75,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Lettuce,None,None,None,None,None,None,9.806701

In [ ]:
data1['item_price_rel'] = merged_df['quantity'] * merged_df['item_pricequantity']

In [ ]:
data1.item_price_rel=data1.item_price_rel.round(decimals=2)

In [ ]:
del data1['item_price']

In [ ]:
data1

,order_id,quantity,item_name,1_choice,2_choice,3_choice,4_choice,5_choice,6_choice,7_choice,8_choice,9_choice,10_choice,item_price_rel
0,1,1,Chips and Fresh Tomato Salsa,None,None,None,None,None,None,None,None,None,None,2.74
1,1,1,Izze,Clementine,None,None,None,None,None,None,None,None,None,3.39
2,1,1,Nantucket Nectar,Apple,None,None,None,None,None,None,None,None,None,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,None,None,None,None,None,None,None,None,None,2.39
4,2,2,Chicken Bowl,TomatilloRed Chili Salsa (Hot),Black Beans,Rice,Cheese,Sour Cream,None,None,None,None,None,19.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4558,1833,1,Steak Burrito,Fresh Tomato Salsa,Rice,Black Beans,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,10.00
4559,1833,1,Steak Burrito,Fresh Tomato Salsa,Rice,Sour Cream,Cheese,Lettuce,Guacamole,None,None,None,None,10.00
4560,1834,1,Chicken Salad Bowl,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Guacamole,Lettuce,None,None,None,None,None,9.81
4561,1834,1,Chicken Salad Bowl,Fresh Tomato Salsa,Fajita Vegetables,Lettuce,None,None,None,None,None,None,None,9.81
4562,1834,1,Chicken Salad Bowl,Fresh Tomato Salsa,Fajita Vegetables,Pinto Beans,Lettuce,None,None,None,None,None,None,9.81